cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-versions'
tap 'derailed/k9s'

brew 'spaceman-diff'
brew 'wget'
brew 'yt-dlp'
brew 'derailed/k9s/k9s'
brew 'kubernetes-cli'
brew 'nvm'
brew 'commitizen'
brew 'powerlevel10k'
brew 'direnv'

cask 'google-chrome-canary'
cask 'notion'
cask 'sonos'
cask 'visual-studio-code'
cask 'vlc'
cask 'swiftbar'
cask 'appcleaner'
cask 'rectangle'
cask 'docker'
cask 'microsoft-teams'
cask 'slack'
cask 'microsoft-outlook'
cask 'dozer'
cask 'copyclip'
cask 'maccy'
cask 'lens'
