cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-versions'
tap 'derailed/k9s'
tap 'oven-sh/bun'
tap 'teamookla/speedtest'

# zsh plugins
brew 'powerlevel10k'
brew 'zsh-autosuggestions'

# Python
brew 'pyenv'
brew 'poetry'
# Dev tools
brew 'openssl'
brew 'make'
brew 'gcc'
brew 'wget'
brew 'code-server'
brew 'commitizen'
brew 'direnv'
brew 'jq'
brew 'gitlab-ci-local'
brew 'tinyproxy'
brew 'netcat'
brew 'watchman'
brew 'azure-cli'
brew 'terraform'
brew 'rsync'
brew 'fswatch'
brew 'dnsmasq'
brew 'nikto'
brew 'deno'
brew 'diff-so-fancy'
brew 'gource'
brew 'nmap'
brew 'iproute2mac'
brew 'go'
brew 'kubebuilder'
brew 'tree'
# k8s
brew 'derailed/k9s/k9s'
brew 'kubernetes-cli'
brew 'kind'
brew 'k3d'
brew 'argocd'
brew 'helm'
brew 'kustomize'
brew 'tilt'
# iOS
brew 'fastlane'
brew 'cocoapods'
brew 'ios-deploy'
# Node
brew 'nvm'
brew 'bun'

# other stuff
brew 'yt-dlp'
brew 'ffmpeg'
brew 'imagemagick'
brew 'speedtest'

#### Apps
# Essentials
cask 'google-chrome-canary'
cask 'notion'
cask 'vlc'
cask 'sonos'
cask 'swiftbar'
cask 'appcleaner'
cask 'rectangle'
cask 'slack'
cask 'maccy'
cask 'dozer'
cask 'readdle-spark'
cask 'rescuetime'
cask 'transmission'
cask 'prusaslicer'
cask 'pronterface'
cask 'inkscape'
cask 'glance-chamburr'
cask 'openscad'
cask 'monitorcontrol'
# Dev stuff
cask 'visual-studio-code'
cask 'docker'
cask 'lens'
cask 'postico'
cask 'pika'
cask 'ngrok'
cask 'iterm2'
cask 'dbeaver-community'
cask 'figma'
cask 'rapidapi'
cask 'redisinsight'
cask 'cyberduck'
# Photos
cask 'digikam'
# MS Office
cask 'microsoft-word'
cask 'microsoft-excel'
cask 'microsoft-powerpoint'
cask 'microsoft-outlook'
cask 'microsoft-teams'
cask 'microsoft-auto-update'
# Other
cask 'ollama'
cask 'blender'
